### ISSUE TITLE
下载不了，安装不上

### ISSUE THREAD

**Issue by shifeichen** [aliyun/aliyun-secretsmanager-client-go#4]
go get -u github.com/aliyun/aliyun-secretsmanager-client-go
package github.com/aliyun/aliyun-secretsmanager-client-go: no Go files in C:\Users\shifei\GolandProjects\src\github.com\aliyun\aliyun-secretsmanager-client-go

**Comment by yingzhi-aliyun** [comment]
Do you install the project successfully by the command go get -u github.com/aliyun/aliyun-secretsmanager-client-go now
